---

- name: Update upgrade
  become: yes
  raw: apt update -y && apt upgrade -y
  changed_when: False
#
#- name: Wait for automatic system updates
#  raw: while pgrep unattended; do sleep 1; done;
#  changed_when: False

#
#- name: Ensure python2 is installed
#  become: yes
#  become_user: root
#  tags: ['prerequisites', 'install']
#  raw: test -e /usr/bin/python || (apt -y update ; apt install -y python-minimal)
#  changed_when: False
#
